// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkFlowEngine.Infrastructure.DataAccess;

#nullable disable

namespace WorkFlowEngine.Infrastructure.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240417114032_addUniqueKey")]
    partial class addUniqueKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.Action", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RuleOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.ActivityAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("ActionId", "ActivityId")
                        .IsUnique();

                    b.ToTable("ActivitiesActions");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.ActivityDestinationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int>("DestinationTypeID")
                        .HasColumnType("int");

                    b.Property<int>("ValueDataFieldId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("DestinationTypeID");

                    b.HasIndex("ValueDataFieldId");

                    b.ToTable("ActivityDestinationTypes");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.DataField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("DataFields");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.DestinationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("DestinationTypes");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.Process", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.ProcessActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("ProcessId");

                    b.ToTable("ProcessActivities");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.ProcessDataFields", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DataFieldId")
                        .HasColumnType("int");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataFieldId");

                    b.HasIndex("ProcessId");

                    b.ToTable("ProcessDataFields");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.ProcessInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicantNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApplicationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentActivityId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Opened")
                        .HasColumnType("bit");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.Property<string>("TaskUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationNumber");

                    b.HasIndex("CurrentActivityId");

                    b.HasIndex("ProcessId");

                    b.ToTable("ProcessInstances");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.ProcessInstanceDataField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DataFieldId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessInstanceId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("DataFieldId");

                    b.HasIndex("ProcessInstanceId");

                    b.ToTable("ProcessInstanceDataField");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.ProcessInstanceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentActivityId")
                        .HasColumnType("int");

                    b.Property<int>("NextActivityId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessInstanceId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("CurrentActivityId");

                    b.HasIndex("NextActivityId");

                    b.HasIndex("ProcessInstanceId");

                    b.ToTable("processInstanceHistories");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.ProcessInstanceUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProcessInstanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationTypeId");

                    b.HasIndex("ProcessInstanceId");

                    b.ToTable("ProcessInstanceUsers");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.Transition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentActivityId")
                        .HasColumnType("int");

                    b.Property<int>("NextActivityId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("CurrentActivityId");

                    b.HasIndex("NextActivityId");

                    b.HasIndex("ProcessId");

                    b.ToTable("transitions");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.TransitionConditions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BinaryOperator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataFieldId")
                        .HasColumnType("int");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TransitionId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DataFieldId");

                    b.HasIndex("TransitionId", "DataFieldId", "Value", "Operator")
                        .IsUnique();

                    b.ToTable("transitionConditions");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.ActivityAction", b =>
                {
                    b.HasOne("WorkFlowEngine.Domain.Entities.Action", "Action")
                        .WithMany("ActivityActions")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkFlowEngine.Domain.Entities.Activity", "Activity")
                        .WithMany("ActivityActions")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.ActivityDestinationType", b =>
                {
                    b.HasOne("WorkFlowEngine.Domain.Entities.Activity", "Activity")
                        .WithMany("ActivityDestinationTypes")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkFlowEngine.Domain.Entities.DestinationType", "DestinationType")
                        .WithMany("ActivityDestinations")
                        .HasForeignKey("DestinationTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkFlowEngine.Domain.Entities.DataField", "ValueDataField")
                        .WithMany()
                        .HasForeignKey("ValueDataFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("DestinationType");

                    b.Navigation("ValueDataField");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.ProcessActivity", b =>
                {
                    b.HasOne("WorkFlowEngine.Domain.Entities.Activity", "Activity")
                        .WithMany("ProcessActivities")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkFlowEngine.Domain.Entities.Process", "Process")
                        .WithMany("ProcessActivities")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.ProcessDataFields", b =>
                {
                    b.HasOne("WorkFlowEngine.Domain.Entities.DataField", "DataField")
                        .WithMany("ProcessDataFields")
                        .HasForeignKey("DataFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkFlowEngine.Domain.Entities.Process", "Process")
                        .WithMany("ProcessDataFields")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataField");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.ProcessInstance", b =>
                {
                    b.HasOne("WorkFlowEngine.Domain.Entities.Activity", "CurrentActivity")
                        .WithMany()
                        .HasForeignKey("CurrentActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkFlowEngine.Domain.Entities.Process", "Process")
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentActivity");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.ProcessInstanceDataField", b =>
                {
                    b.HasOne("WorkFlowEngine.Domain.Entities.DataField", "DataField")
                        .WithMany()
                        .HasForeignKey("DataFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkFlowEngine.Domain.Entities.ProcessInstance", "ProcessInstance")
                        .WithMany("ProcessInstanceDataFields")
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataField");

                    b.Navigation("ProcessInstance");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.ProcessInstanceHistory", b =>
                {
                    b.HasOne("WorkFlowEngine.Domain.Entities.Action", "Action")
                        .WithMany()
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkFlowEngine.Domain.Entities.Activity", "CurrentActivity")
                        .WithMany()
                        .HasForeignKey("CurrentActivityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WorkFlowEngine.Domain.Entities.Activity", "NextActivity")
                        .WithMany()
                        .HasForeignKey("NextActivityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WorkFlowEngine.Domain.Entities.ProcessInstance", "ProcessInstance")
                        .WithMany("ProcessInstanceHistories")
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("CurrentActivity");

                    b.Navigation("NextActivity");

                    b.Navigation("ProcessInstance");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.ProcessInstanceUser", b =>
                {
                    b.HasOne("WorkFlowEngine.Domain.Entities.DestinationType", "DestinationType")
                        .WithMany()
                        .HasForeignKey("DestinationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkFlowEngine.Domain.Entities.ProcessInstance", "ProcessInstance")
                        .WithMany("ProcessInstanceUsers")
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DestinationType");

                    b.Navigation("ProcessInstance");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.Transition", b =>
                {
                    b.HasOne("WorkFlowEngine.Domain.Entities.Action", "Action")
                        .WithMany()
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkFlowEngine.Domain.Entities.Activity", "CurrentActivity")
                        .WithMany()
                        .HasForeignKey("CurrentActivityId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("WorkFlowEngine.Domain.Entities.Activity", "NextActivity")
                        .WithMany()
                        .HasForeignKey("NextActivityId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("WorkFlowEngine.Domain.Entities.Process", "Process")
                        .WithMany("Transitions")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("CurrentActivity");

                    b.Navigation("NextActivity");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.TransitionConditions", b =>
                {
                    b.HasOne("WorkFlowEngine.Domain.Entities.DataField", "DataField")
                        .WithMany()
                        .HasForeignKey("DataFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkFlowEngine.Domain.Entities.Transition", "Transition")
                        .WithMany("TransitionConditions")
                        .HasForeignKey("TransitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataField");

                    b.Navigation("Transition");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.Action", b =>
                {
                    b.Navigation("ActivityActions");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.Activity", b =>
                {
                    b.Navigation("ActivityActions");

                    b.Navigation("ActivityDestinationTypes");

                    b.Navigation("ProcessActivities");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.DataField", b =>
                {
                    b.Navigation("ProcessDataFields");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.DestinationType", b =>
                {
                    b.Navigation("ActivityDestinations");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.Process", b =>
                {
                    b.Navigation("ProcessActivities");

                    b.Navigation("ProcessDataFields");

                    b.Navigation("Transitions");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.ProcessInstance", b =>
                {
                    b.Navigation("ProcessInstanceDataFields");

                    b.Navigation("ProcessInstanceHistories");

                    b.Navigation("ProcessInstanceUsers");
                });

            modelBuilder.Entity("WorkFlowEngine.Domain.Entities.Transition", b =>
                {
                    b.Navigation("TransitionConditions");
                });
#pragma warning restore 612, 618
        }
    }
}
